# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured:
            security: true
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/checkIn, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: ROLE_USER_WYKOP }
        - { path: ^/training/new$, roles: ROLE_USER_WYKOP }
        - { path: ^/lastDistances/([0-9]+)$, roles: ROLE_USER_WYKOP }
        #- { path: ^/training/([0-9]+)?$, method: GET,roles: ROLE_USER_WYKOP }
        - { path: ^/training/$, method: POST,roles: ROLE_USER_WYKOP }
        - { path: ^/, roles: ROLE_ADMIN }
    
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER,ROLE_USER_WYKOP]