# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    LastDistance:
        class: WykopBundle\Service\LastDistance
        arguments: 
            WykopApi: @WykopApi
            entityManager: @doctrine.orm.entity_manager
    Entry:
        class: WykopBundle\Service\Entry
        arguments:
            WykopApi: @WykopApi
