<?php

namespace WykopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LastDistanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LastDistanceRepository extends EntityRepository
{
    function getByTag($id_tag){
	$sql = 'SELECT to_char(date, \'YYYY-MM-DD\') as date, AVG(distance)::INT as distance FROM last_distance  WHERE id_tag = '. (int)$id_tag .' GROUP BY to_char(date, \'YYYY-MM-DD\') ORDER BY max(date) ASC';
	
	$em = $this->getEntityManager();
	$stmt = $em->getConnection()->prepare($sql);
	$stmt->execute();
	$distances = $stmt->fetchAll();
	
	return $distances;
    }
}